apec/config/routes.rb
Apec::Application.routes.draw do
  resources :friend_lists

  resources :chats

  resources :users
root :to => "users#login"

match "validate_access" => "users#validate_access"

end

apec/app/models/chat.rb
class Chat < ActiveRecord::Base
  


  Pusher.app_id ='37864'
  Pusher.key ='e299e24202f901e7f8b8'
  Pusher.secret ='35a058bac34cbfdc3198'

  after_create :send_to_pusher
  def send_to_pusher
    logger.info "Hi?"
    Pusher['APEC'].trigger("chat:create", self.to_json)
  end

end

apec/app/models/friend_list.rb
class FriendList < ActiveRecord::Base
  belongs_to :user
end

apec/app/models/user.rb
class User < ActiveRecord::Base
	has_many :friend_lists
	
end

apec/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

apec/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  # GET /chats
  # GET /chats.json
  def index
  @chats = Chat.all
  @chat = Chat.new(params[:chat])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chats }
    end
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
    @chat = Chat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chat }
    end
  end

  # GET /chats/new
  # GET /chats/new.json
  def new
    @chat = Chat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chat }
    end
  end

  # GET /chats/1/edit
  def edit
    @chat = Chat.find(params[:id])
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(params[:chat])
    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render json: @chat, status: :created, location: @chat }
      else
        format.html { render action: "new" }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chats/1
  # PUT /chats/1.json
  def update
    @chat = Chat.find(params[:id])

    respond_to do |format|
      if @chat.update_attributes(params[:chat])
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat = Chat.find(params[:id])
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url }
      format.json { head :no_content }
    end
  end
end

apec/app/controllers/friend_lists_controller.rb
class FriendListsController < ApplicationController
  # GET /friend_lists
  # GET /friend_lists.json
  def index
   @users = User.all
    @user = User.new(params[:user])
    @friend_lists = FriendList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friend_lists }
    end
  end

  # GET /friend_lists/1
  # GET /friend_lists/1.json
  def show
    @friend_list = FriendList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friend_list }
    end
  end

  # GET /friend_lists/new
  # GET /friend_lists/new.json
  def new
    @friend_list = FriendList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friend_list }
    end
  end

  # GET /friend_lists/1/edit
  def edit
    @friend_list = FriendList.find(params[:id])
  end

  # POST /friend_lists
  # POST /friend_lists.json
  def create
    @friend_list = FriendList.new(params[:friend_list])

    respond_to do |format|
      if @friend_list.save
        format.html { redirect_to @friend_list, notice: 'Friend list was successfully created.' }
        format.json { render json: @friend_list, status: :created, location: @friend_list }
      else
        format.html { render action: "new" }
        format.json { render json: @friend_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friend_lists/1
  # PUT /friend_lists/1.json
  def update
    @friend_list = FriendList.find(params[:id])

    respond_to do |format|
      if @friend_list.update_attributes(params[:friend_list])
        format.html { redirect_to @friend_list, notice: 'Friend list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friend_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_lists/1
  # DELETE /friend_lists/1.json
  def destroy
    @friend_list = FriendList.find(params[:id])
    @friend_list.destroy

    respond_to do |format|
      format.html { redirect_to friend_lists_url }
      format.json { head :no_content }
    end
  end
end

apec/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def login
    @users = User.all
    @user = User.new(params[:user])
  end

  def validate_access
       $user = User.new(params[:user])
    if User.find_by_email_and_name($user.email, $user.name)
      redirect_to users_url
    else
      @validation_message = "The user or password are wrong."
    end      
  end


  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

apec/app/helpers/application_helper.rb
module ApplicationHelper
end

apec/app/helpers/chats_helper.rb
module ChatsHelper
end

apec/app/helpers/friend_lists_helper.rb
module FriendListsHelper
end

apec/app/helpers/users_helper.rb
module UsersHelper
end

apec/app/views/chats/_form.html.erb
<%= form_for(@chat, :remote => true) do |f| %>
 
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.collection_select(:name, User.all, :name, :name ) %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

apec/app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

apec/app/views/chats/index.html.erb
<h1>Listing chats</h1>

<ul id="chat_container">
<% @chats.each do |chat| %>
 <script type="text/javascript">
 
 </script> 
    <li><%= chat.name %> dijo: <%= chat.message %>
    </li>     
  
<% end %>
</ul>
<%= render 'form' %>

<script type="text/javascript">
  Pusher.log = function(message){
    if(window.console && window.console.log)window.console.log(message);

  };

  WEB_SOCKET_DEBUG = true;

  var pusher = new Pusher('e299e24202f901e7f8b8')
  var channel = pusher.subscribe('APEC');

  channel.bind('chat:create', function(data){
    var message = "<li id='chat_"+ data.id +"'>"
        message += data.name +":"+ data.message
        message += "</li>"

        $("#chat_container").append(message);
        $("#message_content").val("");
        $("#message_content").focus();


  });

</script>

apec/app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

apec/app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @chat.message %>
</p>

<p>
  <b>Name<b>
  <%= @chat.name %>
</p>


<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

apec/app/views/friend_lists/_form.html.erb
<%= form_for(@friend_list) do |f| %>
  <% if @friend_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend_list.errors.count, "error") %> prohibited this friend_list from being saved:</h2>

      <ul>
      <% @friend_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Idfriend %><br />
    <%= f.text_field :Idfriend %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

apec/app/views/friend_lists/edit.html.erb
<h1>Editing friend_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend_list %> |
<%= link_to 'Back', friend_lists_path %>

apec/app/views/friend_lists/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.lastname %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friend list', new_friend_list_path %>

apec/app/views/friend_lists/new.html.erb
<h1>New friend_list</h1>

<%= render 'form' %>

<%= link_to 'Back', friend_lists_path %>

apec/app/views/friend_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Idfriend:</b>
  <%= @friend_list.Idfriend %>
</p>

<p>
  <b>User:</b>
  <%= @friend_list.user %>
</p>


<%= link_to 'Edit', edit_friend_list_path(@friend_list) %> |
<%= link_to 'Back', friend_lists_path %>

apec/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apec</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="http://js.pusher.com/1.12/pusher.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

apec/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

apec/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

apec/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.lastname %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Ir al Chat', chats_path %>

<%= link_to 'Buscar Amigos', friend_lists_path %>

apec/app/views/users/login.html.erb

<br />

<%= form_for(@user, :url => "validate_access") do |f| %>
  <div class="field">
    <%= f.label("Email") %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label("Password") %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Register', new_user_path %>

apec/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

apec/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Lastname:</b>
  <%= @user.lastname %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

apec/app/views/users/validate_access.html.erb
<p>
	<%= @validation_message %>
</p>